# Tomcat
server:
  port: 8085

spring:
  application:
    name: client
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.146.134:8848
      username: nacos
      password: Cnbm123456!
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.146.134:3306/ry-vue?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root


